/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratoriofm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ranbr
 */
public class Devolucion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Devolucion
     */
    public Devolucion() {
        initComponents();
        
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "Polo.2015");
            PreparedStatement pst = cn.prepareStatement("select Codigo_R from Rentas ");
            ResultSet rs = pst.executeQuery();
            
          
            
            cbox_Renta.addItem("Seleccione una opción");
            while(rs.next()){
            cbox_Renta.addItem(rs.getString("Codigo_R"));
            }
  
        }catch (Exception e){

        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Dev = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbox_Renta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lb_Venc = new javax.swing.JLabel();
        date_Fecha = new com.toedter.calendar.JDateChooser();

        jLabel3.setText("jLabel3");

        setTitle("Devolucion");

        jLabel1.setText("Codigo Devolucion");

        jLabel2.setText("Codigo Renta");

        cbox_Renta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_RentaActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha Devolucion");

        btnIngresar.setText("Devolucion");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lb_Venc.setText("Vencimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Dev)
                            .addComponent(cbox_Renta, 0, 38, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresar)
                    .addComponent(lb_Venc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Dev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbox_Renta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Venc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnIngresar)
                    .addComponent(date_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void cbox_RentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_RentaActionPerformed
   
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/LabFM", "root", "Polo.2015");
            PreparedStatement pst = cn.prepareStatement("select Fecha_Vencimiento from Rentas where Codigo_R = ?");
            pst.setString(1, cbox_Renta.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){
            lb_Venc.setText(rs.getString("Fecha_Vencimiento"));
            String fecha=lb_Venc.getText().trim();
            String fecha_A=date_Fecha.toString();
            
            //boolean res= fecha_A.before(fecha);
    

            } else {
                JOptionPane.showMessageDialog(null, "Renta no registrada.");
            }

        }catch (Exception e){

        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_cbox_RentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cbox_Renta;
    private com.toedter.calendar.JDateChooser date_Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_Venc;
    private javax.swing.JTextField txt_Dev;
    // End of variables declaration//GEN-END:variables
}
